// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Database;

namespace server.Migrations
{
    [DbContext(typeof(LolContext))]
    partial class LolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("server.Database.Entities.Champion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApiId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Champions");
                });

            modelBuilder.Entity("server.Database.Entities.ChampionList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChampionLists");
                });

            modelBuilder.Entity("server.Database.Entities.ChampionListChampion", b =>
                {
                    b.Property<Guid>("ChampionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChampionListId")
                        .HasColumnType("uuid");

                    b.HasKey("ChampionId", "ChampionListId");

                    b.HasIndex("ChampionListId");

                    b.ToTable("ChampionListChampion");
                });

            modelBuilder.Entity("server.Database.Entities.ChampionListChampion", b =>
                {
                    b.HasOne("server.Database.Entities.Champion", "Champion")
                        .WithMany("ChampionListChampions")
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Database.Entities.ChampionList", "ChampionList")
                        .WithMany("ChampionListChampions")
                        .HasForeignKey("ChampionListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
